services:
  app:
    build:
      context: ./docker
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"  # expõe o php artisan serve
    command: sh -c "if [ -d vendor ]; then php artisan serve --host=0.0.0.0 --port=8000; else echo 'Diretório vendor não encontrado. O contêiner está aguardando a instalação das dependências. Execute php setup.php'; tail -f /dev/null; fi"
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

networks:
  laravel:
    name: laravel
    driver: bridge
