version: '3.8'

services:
  app:
    build:
      context: ./docker
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"  # expõe o php artisan serve
    #command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"
    command: sh -c "if [ -f artisan ]; then php artisan serve --host=0.0.0.0 --port=8000; else echo 'Laravel não encontrado. Entre no container e rode o composer create-project'; tail -f /dev/null; fi"
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
